const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
const watchdog=setTimeout(()=>{console.error('Full import test timed out');process.exit(1)},60000);watchdog.unref();
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.TF_BROWSER_CHANNEL||undefined});try{const page=await browser.newPage({viewport:{width:390,height:844}});await page.route('**/*',route=>{if(route.request().isNavigationRequest())return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'});return route.abort();});await page.goto('http://tf-import.test');console.log('Test origin ready');
for(const path of ['mobile-chrome-shim.js','assets/dashboard-mobile.js','mobile-data-bridge.js']){await page.addScriptTag({path});console.log('Loaded',path);}await page.evaluate(()=>{document.documentElement.dataset.tfServerAuthorized='1';document.dispatchEvent(new Event('DOMContentLoaded'));});await page.addScriptTag({path:'mobile-app-shell.js'});await page.addScriptTag({path:'mobile-import-fix-v30.js'});await page.waitForTimeout(1600);
const client=await page.context().newCDPSession(page);await client.send('Emulation.setCPUThrottlingRate',{rate:4});console.log('Boot complete; beginning import');
await page.locator('#tf-risk-explainer-understand').click();
const result=await page.evaluate(async()=>{window.renderCalls=0;const original=recomputeHistoryRows;recomputeHistoryRows=function(){renderCalls++;return original.apply(this,arguments)};const history=Array.from({length:4348},(_,i)=>({analyst:'Test '+i%9,pair:'XAUUSD',pips:i%4===0?-200:400,sortKey:Date.parse('2025-01-01')+i*10000000,createdSortKey:Date.parse('2025-01-01')+i*10000000-3600000,createdDate:'01-01-2025 00:00 WIB',displayDate:'01-01-2025 01:00 WIB',signalId:String(i),entry:'2000',stopLoss:'1980',takeProfit:'2040',type:'Buy'}));const storage={tfHistorySignals:history,tfAnalystSources:Object.fromEntries(Array.from({length:9},(_,i)=>['Test '+i,{url:'https://example.invalid/'+i,pairs:['XAUUSD']}])),tfMonthlyStats:Object.fromEntries(Array.from({length:9},(_,i)=>['Test '+i+' (XAUUSD)',{'2025-01':{pips:100,signals:12},'2025-02':{pips:-20,signals:3}}])),tfScoreHistory:[],tfAvgSlPips:{},tfNoDataPairs:{}};const payload={schema:'tf_multi_analyst_export_v1',storage,localState:{}};let heartbeats=0;const heartbeat=setInterval(()=>heartbeats++,25);const start=performance.now();const outcome=await tfMobileImportFiles([new File([JSON.stringify(payload)],'synthetic-4348.json',{type:'application/json'})]);const saved=await new Promise(r=>chrome.storage.local.get(['tfHistorySignals'],r));clearInterval(heartbeat);return {heartbeats,outcome,ms:performance.now()-start,calls:renderCalls,saved:saved.tfHistorySignals.length,rows:document.querySelectorAll('#history-table tbody tr').length,summaryRows:document.querySelectorAll('#summary-table tbody tr').length};});
console.log('Import returned',JSON.stringify(result));
assert.equal(result.outcome.ok,true);assert.equal(result.saved,4348);assert.equal(result.calls,1,'import must calculate history once');assert.ok(result.heartbeats>0,'import must yield to the UI');assert.ok(result.rows>0);assert.ok(result.summaryRows>=9);assert.ok(result.ms<20000,'synthetic import must finish in 20 seconds');await page.waitForTimeout(1200);const settled=await page.evaluate(()=>renderCalls);assert.equal(settled,1,'boot timers must not repeat the import');const namesStable=await page.evaluate(()=>{const el=document.querySelector('#monthly-table tbody .monthly-sticky-col-2');window.savedNameTarget=el?.querySelector('.tf-analyst-name-color-target');return !!window.savedNameTarget;});assert.ok(namesStable,'monthly analyst risk span exists');await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>window.savedNameTarget.isConnected),true,'mobile layout must retain the risk span');await page.evaluate(()=>setupTradeTimeRangeButtons());assert.ok(await page.locator('#tf-time-range-buttons-table1 button').count()>0);assert.ok(await page.locator('#tf-single-month-select-table1 option').count()>1);assert.equal(await page.locator('#tf-table1-analytics-filter').evaluate(e=>e.nextElementSibling.className),'tf-holding-head');await page.selectOption('#tf-single-month-select-table1','2025-01');assert.equal(await page.evaluate(()=>tfTradeSingleMonthKey),'2025-01');await page.locator('#tf-time-range-buttons-table1 button[data-range="all"]').click();assert.equal(await page.evaluate(()=>tfTradeSingleMonthKey),'');console.log('Table 1 selectors and explanation popup PASS');assert.equal(await page.locator('#tf-balance-cards412').evaluate(e=>!!e.closest('#tf-mobile-performance-screen')),true,'cards belong in Performance nav');
await page.addStyleTag({path:'assets/dashboard-original.css'});await page.addStyleTag({path:'mobile-overrides.css'});
const flow=await page.evaluate(()=>{
 tfTradeTimeRangeKey='all';tfTradeSingleMonthKey='';
 const container=document.querySelector('input[data-analyst="Test 0"]:not([data-pair])').closest('.analyst-filter-list').parentElement;
 const select=name=>document.querySelector('#'+container.id+' input[data-analyst="'+name+'"]:not([data-pair])');
 container.querySelector('input:not([data-analyst])').click();
 const result=[{stage:'none',points:equityCurvePoints.length}];
 const record=stage=>result.push({stage,analysts:Array.from(new Set(equityCurvePoints.filter(p=>!p.isStart).map(p=>p.analyst))),last:equityCurvePoints.at(-1)?.sortKey,end:equityFilterEnd,count:equityCurvePoints.length,expected:lastHistoryRows.filter(r=>tf_isHistoryRowEnabled(r)).length,card:document.querySelectorAll('.tf-balance-value412')[1].textContent,range:tfTradeTimeRangeKey});
 select('Test 0').click();record('A');select('Test 1').click();record('AB');select('Test 0').click();record('B');
 return result;
});
assert.equal(flow[0].points,0);assert.deepEqual(flow[1].analysts,['Test 0']);assert.deepEqual(flow[2].analysts.sort(),['Test 0','Test 1']);assert.deepEqual(flow[3].analysts,['Test 1']);assert.equal(flow[3].range,'all');assert.equal(flow[3].last,flow[3].end);assert.ok(flow[3].count>2);await page.waitForTimeout(2450);assert.equal(await page.evaluate(()=>tfEquityAnimation412),null);await page.evaluate(()=>drawEquityCurve());
console.log('Actual checkbox selection → chart → Performance cards PASS',JSON.stringify(flow));
console.log(JSON.stringify(result));
}catch(e){throw e}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});

