const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const watchdog=setTimeout(()=>{console.error('Mobile production-order verification timed out');process.exit(1)},90000);watchdog.unref();
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.TF_BROWSER_CHANNEL||undefined});try{const page=await browser.newPage({viewport:{width:390,height:844}});await page.route('**/*',r=>r.request().isNavigationRequest()?r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}):r.abort());await page.goto('http://tf-mobile414.test');await page.evaluate(()=>document.documentElement.dataset.tfServerAuthorized='1');await page.addStyleTag({path:'assets/dashboard-original.css'});await page.addStyleTag({path:'mobile-overrides.css'});
// Match mobile-license-gate exactly: app shell is loaded before DOMContentLoaded.
for(const path of ['mobile-chrome-shim.js','assets/dashboard-mobile.js','mobile-data-bridge.js','mobile-app-shell.js'])await page.addScriptTag({path});await page.evaluate(()=>document.dispatchEvent(new Event('DOMContentLoaded',{bubbles:true})));await page.waitForTimeout(1700);await page.locator('#tf-risk-explainer-understand').click();await page.locator('[data-mobile-nav="performance"]').click();
async function visibleCards(stage){assert.equal(await page.locator('#tf-balance-cards412').evaluate(e=>e.parentElement.id),'tf-mobile-performance-screen');assert.equal(await page.locator('.tf-balance-card412').count(),4);for(const card of await page.locator('.tf-balance-card412').all()){assert.equal(await card.isVisible(),true,stage);const rect=await card.boundingBox();assert.ok(rect.width>70 && rect.height>40,stage)}assert.deepEqual(await page.locator('.tf-balance-label412').allTextContents(),['Saldo','Equity $','PnL $','PnL %']);}
await visibleCards('before import');
await page.evaluate(async()=>{const start=Date.parse('2025-01-01');const history=Array.from({length:960},(_,i)=>({analyst:'A',pair:'XAUUSD',pips:i%4===0?-200:400,sortKey:start+i*86400000,createdSortKey:start+i*86400000-3600000,createdDate:'01-01-2025 00:00 WIB',displayDate:'01-01-2025 01:00 WIB',signalId:String(i),entry:'2000',stopLoss:'1980',takeProfit:'2040',type:'Buy'}));const storage={tfHistorySignals:history,tfAnalystSources:{A:{url:'https://example.invalid/A',pairs:['XAUUSD']}},tfMonthlyStats:{'A (XAUUSD)':{'2025-01':{pips:100,signals:12},'2027-08':{pips:100,signals:12}}},tfScoreHistory:[],tfAvgSlPips:{},tfNoDataPairs:{}};const result=await tfMobileImportFiles([new File([JSON.stringify({schema:'tf_multi_analyst_export_v1',storage,localState:{}})],'fixture.json',{type:'application/json'})]);if(!result.ok)throw new Error('Import failed')});await page.locator('[data-mobile-nav="performance"]').click();await visibleCards('after import');
for(const width of [390,768]){await page.setViewportSize({width,height:844});await page.waitForTimeout(450);await visibleCards('viewport '+width);const bounds=await page.locator('#tf-balance-cards412').boundingBox();assert.ok(bounds.x>=0 && bounds.x+bounds.width<=width+1);}
await page.setViewportSize({width:390,height:844});await page.locator('[data-mobile-nav="equity"]').click();await page.waitForTimeout(2600);
for(const range of ['m1','m2','all','all']){await page.locator('#tf-time-range-buttons-equity button[data-range="'+range+'"]').click();await page.waitForTimeout(120);const early=await page.evaluate(()=>({duration:tfEquityAnimation412?.duration,progress:tfEquityAnimation412?.progress}));assert.equal(early.duration,2200,range);assert.ok(early.progress>=0 && early.progress<.2,range);await page.waitForTimeout(2500);assert.equal(await page.evaluate(()=>tfEquityAnimation412),null,range)}
await page.locator('[data-mobile-nav="performance"]').click();await visibleCards('after timeframe changes');const values=await page.locator('.tf-balance-value412').allTextContents();assert.ok(values.every(v=>v!=='—'),'actual data populate every card');const stored=await page.evaluate(()=>window.__tfBalanceCardsState414);const rowEquity=await page.evaluate(()=>Number(tf_lastEquityCalcRows.at(-1)?.balancePnl));assert.equal(stored.equity,rowEquity);await page.screenshot({path:'/tmp/mobile414-performance.png'});console.log('Production script order: 4 visible Performance cards before/after import, portrait/tablet, actual balance values; m1/m2/ALL/repeated ALL animation PASS',JSON.stringify(values));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
