const assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.TF_BROWSER_CHANNEL||(process.env.CI?undefined:'chrome')});try{
const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>r.request().isNavigationRequest()?r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}):r.abort());await page.goto('https://mobile474.test');
await page.evaluate(()=>document.documentElement.dataset.tfServerAuthorized='1');
for(const file of ['assets/dashboard-original.css','mobile-overrides.css'])await page.addStyleTag({path:file});
for(const file of ['mobile-chrome-shim.js','assets/dashboard-mobile.js','mobile-data-bridge.js','assets/tf-analyst-risk-adjustment.js','assets/tf-analyst-report.js','assets/tf-dashboard-performance.js','mobile-app-shell.js'])await page.addScriptTag({path:file});
await page.evaluate(()=>document.dispatchEvent(new Event('DOMContentLoaded',{bubbles:true})));await page.waitForTimeout(1800);await page.locator('#tf-risk-explainer-understand').click();
assert.equal(await page.locator('#tf-pair-value-adjustment>details>summary').innerText(),'Table Adjustment Value of Pairs - Hide');assert.equal(await page.locator('#tf-analyst-risk-adjustment').evaluate(e=>e.nextElementSibling.id),'tf-pair-value-adjustment');assert.equal(await page.locator('.tf-risk-fold').getAttribute('open'),null);assert.equal(await page.locator('.tf-lot-fold').getAttribute('open'),null);assert.equal(await page.locator('#summary-table').isVisible(),false);
assert.equal(await page.locator('#tf-pair-value-adjustment .pip-table-compact').count(),2);assert.equal(await page.locator('#tf-pair-value-adjustment .pip-table-compact').first().isVisible(),false);await page.locator('.tf-price-fold>summary').click();assert.equal(await page.locator('#tf-pair-value-adjustment .pip-table-compact').first().isVisible(),true);await page.locator('.tf-lot-fold>summary').click();assert.equal(await page.locator('#summary-table').isVisible(),true);
await page.evaluate(()=>{historySignals=[{analyst:'Sample',pair:'XAUUSD',pips:100,sortKey:new Date(2026,2,2).getTime()},{analyst:'Sample',pair:'XAUUSD',pips:-200,sortKey:new Date(2026,9,2).getTime()}];analystSourcesByName={Sample:{url:'https://example.com/analyst'}};});
assert.equal(await page.locator('.tf-risk-fold>summary').evaluate(el=>getComputedStyle(el).fontSize),await page.locator('#tf-user-adjustment415>legend').evaluate(el=>getComputedStyle(el).fontSize));await page.locator('[data-mobile-nav="report"]').click();assert.match(await page.locator('#tf-report-explainer').innerText(),/dibagi 4/);assert.equal(await page.locator('#tf-report-explainer .tf-risk-explainer-row').count(),2);assert.equal(await page.locator('#tf-report-explainer .tf-risk-green').count(),0);assert.equal(await page.locator('#tf-report-explainer h2').innerText(),'Analis Report');await page.locator('#tf-report-explainer button').click();
assert.equal(await page.locator('#tf-analyst-report').isVisible(),true);assert.equal(await page.locator('#tf-analyst-report #tf-analyst-risk-adjustment').count(),1);assert.equal(await page.locator('#tf-analyst-report #tf-user-adjustment415').isVisible(),true);
assert.equal(await page.locator('#tf-analyst-report tbody tr').count(),1);assert.equal(await page.locator('#tf-analyst-report a[target="_blank"]').getAttribute('href'),'https://example.com/analyst');
await page.locator('#tf-analyst-report .tf-risk-fold>summary').click();await page.locator('#tf-analyst-report [data-risk=cons]').fill('45');await page.locator('#tf-analyst-report [data-risk=cons]').dispatchEvent('change');assert.equal(await page.evaluate(()=>tf_analystRiskSettings().cons),30);await page.locator('.tf-risk-confirm').click();assert.equal(await page.evaluate(()=>tf_analystRiskSettings().cons),45);
await page.locator('[data-mobile-nav="table1"]').click();assert.equal(await page.locator('#tf-analyst-report').isVisible(),false);assert.equal(await page.locator('#section-summary #tf-analyst-risk-adjustment').count(),1);
await page.locator('[data-mobile-nav="performance"]').click();assert.equal(await page.locator('#tf-user-adjustment415').isVisible(),true);await page.locator('[data-mobile-nav="report"]').click();
assert.equal(await page.locator('#tf-analyst-report #tf-user-adjustment415').isVisible(),true);assert.equal(await page.locator('.tf-report-pnl-pair').count(),4);
await page.locator('#tf-report-explainer').count();await page.screenshot({path:'../../outputs/mobile482-report.png'});assert.deepEqual(errors,[]);console.log('PASS actual mobile production order, Report navigation, shared risk inputs, fold controls, Performance restore, no runtime errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

